DROP DATABASE IF EXISTS BaseA;
CREATE DATABASE BaseA CHARACTER SET utf8;

USE BaseA;

DROP TABLE IF EXISTS Config;

CREATE TABLE Config(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    txt_penColor CHAR(7) NOT NULL,
    txt_fillColor CHAR(7) NOT NULL,
    int_accountId INT NOT NULL,
    int_width INT NOT NULL,
    int_radius INT NOT NULL
);

DROP TABLE IF EXISTS Account;

CREATE TABLE Account(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    txt_role CHAR(8) NOT NULL DEFAULT "Operator",
    txt_name TEXT NOT NULL,
    txt_password TEXT NOT NULL
);

DROP TABLE IF EXISTS Drawing;

CREATE TABLE Drawing(
   int_accountID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
   tim_date TIMESTAMP NOT NULL,
   jso_file JSON
);
/*
DROP TABLE IF EXISTS Record;
CREATE TABLE Record(
    
);

*/
